### ISSUE TITLE
Problem with Calculating standard deviations for all samples step

### ISSUE THREAD

**Issue by vyomeshj209** [shwetaramdas/conifer_python3#3]
Error:

done!
[RUNNING] Calculating standard deviations for all samples (this can take a while)...
Traceback (most recent call last):
  File "/home/ubuntu/CNV_tools/conifer/conifer_python3-main/conifer.py", line 718, in <module>
    args.func(args)
  File "/home/ubuntu/CNV_tools/conifer/conifer_python3-main/conifer.py", line 256, in CF_analyze
    sd_out = h5file_out.root._f_getChild("chr%d" % chr)._f_getChild("sample_%s" % s).read(field="rpkm").flatten()
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/tables/group.py", line 798, in __getattr__
    return self._f_get_child(name)
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/tables/group.py", line 682, in _f_get_child
    self._g_check_has_child(childname)
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/tables/group.py", line 375, in _g_check_has_child
    raise NoSuchNodeError(
tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``_f_getChild``
Closing remaining open files:analysis.hdf5...done

Kindly request your help for the above code error.

**Comment by shwetaramdas** [comment]
Hello, could you please include your command here as well?

**Comment by vyomeshj209** [comment]
Hi Shweta,

Thank you for your response.

Command:
(base) abc@user:~/CNV_tools/conifer/conifer_v0.2.2$ python conifer.py rpkm --input /home/path/ABCX-F/Files/ABCX-F.bam --output ./RPKM/ABCX-F.rpkm.txt --probes /home/path/CNV_tools/conifer/conifer_v0.2.2/probe_region_GRCh37_13_Mar_23.txt

**Comment by vyomeshj209** [comment]
> Hello, could you please include your command here as well?

Hi Shweta,

Thank you for your response.

Command:
(base) abc@user:~/CNV_tools/conifer/conifer_v0.2.2$ python conifer.py rpkm --input /home/path/ABCX-F/Files/ABCX-F.bam --output ./RPKM/ABCX-F.rpkm.txt --probes /home/path/CNV_tools/conifer/conifer_v0.2.2/probe_region_GRCh37_13_Mar_23.txt

Command is generating the analysis.hdf5 file. Only getting stuck at the standard deviation phase.
